-- Build TECHBOOK database and tables --

-- Create the TECHBOOK database

DROP DB TECHBOOK; 
CREATE DB TECHBOOK;

UPDATE DB CFG FOR TECHBOOK USING APPLHEAPSZ 256; 
 
-- Commit to save work
COMMIT WORK;

GRANT ALL ON TECHBOOK TO PUBLIC; 
 
CREATE SCHEMA LIB; 

-- Commit to save work
COMMIT WORK;

CONNECT RESET;

-- Create the BOOK_CATALOG table

CONNECT to TECHBOOK;


-- DROP TABLE LIB.BOOK_CATALOG;

CREATE TABLE LIB.BOOK_CATALOG
  (CATALOG_NUMBER CHARACTER(5) NOT NULL,
   AUTHOR VARCHAR(50) NOT NULL,
   BOOK_TITLE VARCHAR(100) NOT NULL,
   LOCATION VARCHAR(50) NOT NULL,
   PLATFORM CHARACTER(2),
   LANGUAGE CHARACTER(2),
   PRIMARY KEY(CATALOG_NUMBER));

-- GRANT ALL ON BOOK_CATALOG TO PUBLIC; 

-- Commit to save work
COMMIT WORK;

-- Load BOOK_CATALOG Table Data

INSERT INTO LIB.BOOK_CATALOG (CATALOG_NUMBER, AUTHOR, BOOK_TITLE, LOCATION, PLATFORM, LANGUAGE)
VALUES('00001', 'Developer Journal', 'Windows NT Programming in Practice', 'Library', '04', '02');
 	
INSERT INTO LIB.BOOK_CATALOG (CATALOG_NUMBER, AUTHOR, BOOK_TITLE, LOCATION, PLATFORM, LANGUAGE)
VALUES('00002', 'Chris Hare', 'Inside Unix', 'AAA_Company', '00', '02');

INSERT INTO LIB.BOOK_CATALOG (CATALOG_NUMBER, AUTHOR, BOOK_TITLE, LOCATION, PLATFORM, LANGUAGE)
VALUES('00003', 'David Flanagan and a team', 'Java Enterprise in a Nutshell', 'Library', '00', '01');

INSERT INTO LIB.BOOK_CATALOG (CATALOG_NUMBER, AUTHOR, BOOK_TITLE, LOCATION, PLATFORM, LANGUAGE)
VALUES('00004', 'Danny  Ayers and a team', 'Java Server Programming', 'BBB_Company', '00', '01');

INSERT INTO LIB.BOOK_CATALOG (CATALOG_NUMBER, AUTHOR, BOOK_TITLE, LOCATION, PLATFORM, LANGUAGE)
VALUES('00005', 'Bill McCarty', 'Learn Red Hat Linux', 'Library', '05', '01');

INSERT INTO LIB.BOOK_CATALOG (CATALOG_NUMBER, AUTHOR, BOOK_TITLE, LOCATION, PLATFORM, LANGUAGE)
VALUES('00006', 'Lisa Donald and a team', 'MCSE Windows 2000 Professional', 'BBB_Company', '04', '02');

INSERT INTO LIB.BOOK_CATALOG (CATALOG_NUMBER, AUTHOR, BOOK_TITLE, LOCATION, PLATFORM, LANGUAGE)
VALUES('00007', 'Harry M. Brelsford', 'Windows 2000 Server Secrets', 'BBB_Company', '04', '02');

-- Commit to save work
COMMIT WORK;


-- Create the BOOK_ACTIVITY table

-- DROP TABLE LIB.BOOK_ACTIVITY;

CREATE TABLE LIB.BOOK_ACTIVITY
  (TXN_DATE     CHARACTER(10) NOT NULL,
   TXN_TIME     CHARACTER(8) NOT NULL,
   TXN_TYPE     CHARACTER(4) NOT NULL,
   BOOK_CAT_NUM CHARACTER(5) NOT NULL,
   COMPANY_NAME VARCHAR(50) NOT NULL,
   PRIMARY KEY(TXN_DATE,TXN_TIME));

-- GRANT ALL ON BOOK_ACTIVITY TO PUBLIC; 

-- Commit to save work
COMMIT WORK;


-- Load the BOOK_ACTIVITY table data

INSERT INTO LIB.BOOK_ACTIVITY (TXN_DATE, TXN_TIME, TXN_TYPE , BOOK_CAT_NUM, COMPANY_NAME)
VALUES('01-01-2002', '09:17:25', 'RENT', '00001', 'AAA_Company');

INSERT INTO LIB.BOOK_ACTIVITY (TXN_DATE, TXN_TIME, TXN_TYPE , BOOK_CAT_NUM, COMPANY_NAME)
VALUES('01-10-2002', '10:11:66', 'RETR', '00001', 'AAA_Company');

INSERT INTO LIB.BOOK_ACTIVITY (TXN_DATE, TXN_TIME, TXN_TYPE , BOOK_CAT_NUM, COMPANY_NAME)
VALUES('02-20-2002', '11:12:55', 'RENT', '00002', 'AAA_Company');

INSERT INTO LIB.BOOK_ACTIVITY (TXN_DATE, TXN_TIME, TXN_TYPE , BOOK_CAT_NUM, COMPANY_NAME)
VALUES('01-15-2002', '12:12:12', 'RENT', '00003', 'BBB_Company');

INSERT INTO LIB.BOOK_ACTIVITY (TXN_DATE, TXN_TIME, TXN_TYPE , BOOK_CAT_NUM, COMPANY_NAME)
VALUES('01-31-2002', '13:26:33', 'RETR', '00003', 'BBB_Company');

INSERT INTO LIB.BOOK_ACTIVITY (TXN_DATE, TXN_TIME, TXN_TYPE , BOOK_CAT_NUM, COMPANY_NAME)
VALUES('03-05-2002', '14:22:11', 'RENT', '00003', 'CCC_Company');

INSERT  INTO LIB.BOOK_ACTIVITY (TXN_DATE, TXN_TIME, TXN_TYPE , BOOK_CAT_NUM, COMPANY_NAME)
VALUES('04-05-2002', '15:44:31', 'RETR', '00003', 'CCC_Company');

INSERT INTO LIB.BOOK_ACTIVITY (TXN_DATE, TXN_TIME, TXN_TYPE , BOOK_CAT_NUM, COMPANY_NAME)
VALUES('02-11-2002', '16:32:33', 'RENT', '00004', 'BBB_Company');

INSERT INTO LIB.BOOK_ACTIVITY (TXN_DATE, TXN_TIME, TXN_TYPE , BOOK_CAT_NUM, COMPANY_NAME)
VALUES('02-17-2002', '17:12:22', 'RENT', '00005', 'BBB_Company');

INSERT INTO LIB.BOOK_ACTIVITY (TXN_DATE, TXN_TIME, TXN_TYPE , BOOK_CAT_NUM, COMPANY_NAME)
VALUES('03-11-2002', '18:23:44', 'RETR', '00005', 'BBB_Company');

INSERT INTO LIB.BOOK_ACTIVITY (TXN_DATE, TXN_TIME, TXN_TYPE , BOOK_CAT_NUM, COMPANY_NAME)
VALUES('03-15-2002', '19:27:11', 'RENT', '00005', 'DDD_Company');

INSERT INTO LIB.BOOK_ACTIVITY (TXN_DATE, TXN_TIME, TXN_TYPE , BOOK_CAT_NUM, COMPANY_NAME)
VALUES('04-12-2002', '20:43:21', 'RETR', '00005', 'DDD_Company');

INSERT INTO LIB.BOOK_ACTIVITY (TXN_DATE, TXN_TIME, TXN_TYPE , BOOK_CAT_NUM, COMPANY_NAME)
VALUES('05-01-2002', '20:11:21', 'RENT', '00006', 'BBB_Company');

INSERT INTO LIB.BOOK_ACTIVITY (TXN_DATE, TXN_TIME, TXN_TYPE , BOOK_CAT_NUM, COMPANY_NAME)
VALUES('05-02-2002', '21:11:21', 'RENT', '00007', 'BBB_Company');

-- Commit to save work
COMMIT WORK;


-- Create the BOOK_NOTIFY table

-- DROP TABLE LIB.BOOK_NOTIFY;

CREATE TABLE LIB.BOOK_NOTIFY
  (MESSAGE_KEY CHARACTER(20) NOT NULL,
   MESSAGE_BODY CHARACTER(250) NOT NULL,
   PRIMARY KEY(MESSAGE_KEY));

-- GRANT ALL ON BOOK_NOTIFY TO PUBLIC; 
   
-- Commit to save work
COMMIT WORK;

-- End the connection
CONNECT RESET;